version: '3.8'


services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - "${SELENIUM_PORT:-4444}:4444"
    restart: unless-stopped
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prefect
    volumes:
      - postgres-data:/var/lib/postgresql/data
  prefect:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PREFECT_HOME=/data
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:password@postgres/prefect
      - SELENIUM_URL=http://selenium:${SELENIUM_PORT:-4444}/wd/hub
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:/data
      - .:/app
    depends_on:
      - selenium
      - postgres
volumes:
  postgres-data:
  prefect-data:
  